name: Deploy Android app for dev

on:
  workflow_dispatch:

jobs:
  build_android:
    name: build android
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup cache
        uses: actions/cache@v3.3.2
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: set up Node.js
        uses: actions/setup-node@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Flutter のバージョンを fvm_config.json から読み取る
      - name: Get Flutter version from fvm_config.json
        id: flutter_version
        run: echo "version=$(jq -r '.flutterSdkVersion' facraft-frontend-app/.fvm/fvm_config.json)" >> $GITHUB_OUTPUT

      # 使用する Flutter のバージョンをセットアップ
      - name: install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: ${{ steps.flutter_version.outputs.version }}
          channel: 'stable'

      - name: flutter dependencies install
        run: flutter pub get

      - name: build apk
        run: |
          flutter build apk --dart-define-from-file=dart_defines/dev.json

      - name: List APK file
        run: ls -l build/app/outputs/flutter-apk/

      - name: Upload artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy_android:
    name: deploy android
    needs: [build_android]
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4.1.0
        with:
          name: android

      # Deploy to Firebase
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: app_testers
